### ISSUE TITLE
JUSTSALAD - Request for New Table Creation 

### ISSUE THREAD

**Issue by vinothk-iq** [vinothk-iq/iqbo-dev-JUSTSALAD#1]
@dgayathri-IQ @niranjanadhamkumar @dkamaraj-IQ @Vraj-IQ 

Hi Team, 

Please create the Restaurant Vendor Items table for **"Performance Foodservice Springfield"** vendor. 

Please create the IQR item template for the listed vendors. 

**Freshpoint
Marcat Inc. DBA Anmar Foods
Midwest Foods
IB&P - Imperial Bag & Paper Co., LLC
Performance Foodservice Springfield**

Regards,
VInoth KS

**Comment by dkamaraj-IQ** [comment]
@vinothkiqbo - Please create a ticket under JUSTSALAD repository and make sure you assign the ticket to the respective team member.

**Comment by vinothk-iq** [comment]
@dkamaraj-IQ thank for your assistance, I have got the IQ domain access from Ed.
