### ISSUE TITLE
Restaurant Table - 08/23/2023  

### ISSUE THREAD

**Issue by vinothk-iq** [vinothk-iq/iqbo-dev-JUSTSALAD#2]
Hi Alvin and Jeremy,

Please add the attached Restaurant Table Data Addition in Archimedes and confirm at earliest.

@aventura-iq @dkamaraj-IQ @niranjanadhamkumar @dgayathri-IQ @brajasekaran-IQ
[JUSTSALAD - Restaurant Table - Data Addition 4.xlsx](https://github.com/vinothk-iq/iqbo-dev-JUSTSALAD/files/12442944/JUSTSALAD.-.Restaurant.Table.-.Data.Addition.4.xlsx)
 @sulaganathan-IQ @jsulit-iq

Regards,
Vinoth KS
[JUSTSALAD - Restaurant Table - Data Addition 4.xlsx](https://github.com/vinothk-iq/iqbo-dev-JUSTSALAD/files/12442870/JUSTSALAD.-.Restaurant.Table.-.Data.Addition.4.xlsx)

**Comment by aventura-iq** [comment]
@vinothk-iq wrong repository. Please close this and create a new ticket in our official repo: https://github.com/iqbo-dev/just-salad/issues

**Comment by vinothk-iq** [comment]
@aventura-iq as per your instruction, i have created the new ticker in the above link.
